GetTweets/Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Web.Script.Serialization;
using LinqToTwitter;
using Newtonsoft.Json;
using GetTweets.ViewModel;
using Models;

namespace GetTweets.Controllers
{
    public class TweetController : Controller
    {
        private static string searchTweet = "#DWTS";
        private static Int64 tweetCount = 10;
        public JsonResult Tweets(Tweet t)
        {          

            var authorizer = new SingleUserAuthorizer
            {
                CredentialStore = new InMemoryCredentialStore()
                {
                    ConsumerKey = ConfigurationManager.AppSettings["ConsumerKey"],
                    ConsumerSecret = ConfigurationManager.AppSettings["ConsumerSecret"],
                    OAuthToken = ConfigurationManager.AppSettings["OAuthToken"],
                    OAuthTokenSecret = ConfigurationManager.AppSettings["OAuthTokenSecret"],
                    ScreenName= ConfigurationManager.AppSettings["ScreenName"],
                    UserID = Convert.ToUInt64(ConfigurationManager.AppSettings["UserID"])                
                }
            };

            var twitterContext = new TwitterContext(authorizer);
            List<Search> statusTweets = new List<Search>();
          
            statusTweets = (from tweet in twitterContext.Search
                                where tweet.Type == SearchType.Search && tweet.Query == searchTweet
                                && tweet.Count == tweetCount
                                && tweet.ResultType == ResultType.Popular
                                select tweet).ToList();
            
            var json = JsonConvert.SerializeObject(new
            {
                operations = statusTweets
            });
            
            var result= Json(json, JsonRequestBehavior.AllowGet);
            var root = new JavaScriptSerializer().Deserialize<RootObject>(result.Data.ToString());
            var ops = root.operations.FirstOrDefault();

            TweetViewModel tvm = new TweetViewModel();
            tvm.tweet = new Tweet() { Message=ops.Query };
            tvm.tweets = new List<Tweet>();

            foreach (var status in ops.Statuses)
            {                
                Tweet twt = new Tweet();
                twt.Message = status.Text;
                twt.LikesCount = status.FavoriteCount;
                twt.TimePosted = status.CreatedAt;
                twt.RetweetCount = status.RetweetCount;
                twt.Author = status.User.Name;
                twt.AuthorPic = status.User.ProfileImageUrl;
                tvm.tweets.Add(twt);
            }
            return Json(tvm, JsonRequestBehavior.AllowGet);            
        }

        public ActionResult Tweet1()
        {           
            var authorizer = new SingleUserAuthorizer
            {
                CredentialStore = new InMemoryCredentialStore()
                {
                    ConsumerKey = ConfigurationManager.AppSettings["ConsumerKey"],
                    ConsumerSecret = ConfigurationManager.AppSettings["ConsumerSecret"],
                    OAuthToken = ConfigurationManager.AppSettings["OAuthToken"],
                    OAuthTokenSecret = ConfigurationManager.AppSettings["OAuthTokenSecret"],
                    ScreenName = ConfigurationManager.AppSettings["ScreenName"],
                    UserID = Convert.ToUInt64(ConfigurationManager.AppSettings["UserID"])
                }
            };

            var twitterContext = new TwitterContext(authorizer);
            List<Search> statusTweets = new List<Search>();

            
        statusTweets = (from tweet in twitterContext.Search
                            where tweet.Type == SearchType.Search && tweet.Query == searchTweet
                            && tweet.Count == tweetCount
                            && tweet.ResultType == ResultType.Popular
                            select tweet).ToList();

            var json = JsonConvert.SerializeObject(new
            {
                operations = statusTweets
            });

            var result = Json(json, JsonRequestBehavior.AllowGet);
            var root = new JavaScriptSerializer().Deserialize<RootObject>(result.Data.ToString());
            var ops = root.operations.FirstOrDefault();

            TweetViewModel tvm = new TweetViewModel();
            tvm.tweet = new Tweet() { Message = ops.Query };
            tvm.tweets = new List<Tweet>();

            foreach (var status in ops.Statuses)
            {
                Tweet twt = new Tweet();
                twt.Message = status.Text;
                twt.LikesCount = status.FavoriteCount;
                twt.TimePosted = status.CreatedAt;
                twt.RetweetCount = status.RetweetCount;
                twt.Author = status.User.Name;
                twt.AuthorPic = status.User.ProfileImageUrl;
                tvm.tweets.Add(twt);
            }
            return View(tvm);
        }

        public ActionResult Home()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

    }
}

GetTweets/Views/Home/Index.cshtml
@model Models.Tweet

@{
    ViewBag.Title = "Get Tweets";
}

<div ng-controller="TwitterViewModel">
    Enter Hash Tag to get tweets: <input id="Text1" ng-model="t.TweetHashTag" type="text" /><br />
    <input id="Button1" type="button" value="Submit" />
    <input id="Button2" type="button" value="Reset" />
</div>

GetTweets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Twitter Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/angular.min.js"></script>
    <script language="javascript">
        var app = angular.module("myApp", []);
        app.controller('TweetViewModel', TweetViewModel);
    </script>
    <script src="~/Scripts/TwitterVM.js"></script>
</head>
<body ng-app="myApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">                
                @Html.ActionLink("Twitter App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Twitter Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GetTweets/Views/Tweet/Home.cshtml
@model GetTweets.ViewModel.TweetViewModel
@using Models;

@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Twitter App</title>    
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>

<body>
    <div>
            @using (Html.BeginForm("Tweet1", "Tweet", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.tweet.TweetHashTag)
                @Html.ValidationMessageFor(model => model.tweet.TweetHashTag)
                <button type="submit">Submit</button>
            }
       
            
       
    </div>
</body>
</html>

GetTweets/Views/Tweet/Home1.cshtml
@model GetTweets.ViewModel.TweetViewModel
@using Models;

@{
    Layout = null;
}


<!DOCTYPE html>
<html ng-app="AngularApp">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Twitter App</title>
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/AppModule.js"></script>
    <script src="~/Scripts/Service.js"></script>
    <script src="~/Scripts/Controller.js"></script>
</head>
<body>
    <div ng-controller="TweetCtrl">
        <div>
            Enter Hash Tag to get tweets: <input id="Text1" ng-model="tweet.TweetHashTag" type="text" /><br />
            <input id="Submit1" type="button" value="Submit" />
            <table border="1" cellpadding="10" align="center">
                <tr>
                    <td>
                        Author
                    </td>
                    <td>
                        Author Pic
                    </td>
                    <td>
                        Message
                    </td>
                    <td>
                        Posted At
                    </td>
                </tr>
                <tr ng-repeat="tvm in tweets">
                    <td>
                        {{tvm.Author}}
                    </td>
                    <td>
                        {{tvm.AuthorPic}}
                    </td>
                    <td>
                        {{tvm.Message}}
                    </td>
                    <td>
                        {{tvm.TimePosted}}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>

GetTweets/Views/Tweet/Tweet1.cshtml
@model GetTweets.ViewModel.TweetViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Twitter App</title>
    <style>
        .Grid td {
            padding: 3px;
        }

        .Grid {
            border-collapse: collapse;
        }

        .GridHeader th {
            background-color: lightblue;
            border: 1px solid black;
        }

        .Grid td {
            background-color: lightgray;
            border: 1px solid black;
        }

        .AltRow td {
            background-color: lightpink;
        }

        .GridFooter td {
            background-color: lightblue;
        }
    </style>
    <script src="~/Scripts/jquery-1.10.2.js"></script>   
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script> 
</head>
<body>
    <b>Enter Hash Tag to get tweets:</b> <input id="Text1" type="text" />
    <input id="Submit1" type="button" value="Submit" /><br/><br />
    @{
        var grid = new WebGrid(Model.tweets, canPage: true,
            canSort: true, rowsPerPage: 2, ajaxUpdateContainerId: "DivGrid");
        grid.Pager(WebGridPagerModes.NextPrevious);
    }
    <div id="DivGrid">
        @grid.GetHtml(tableStyle: "Grid", headerStyle: "GridHeader",
    alternatingRowStyle: "AltRow", footerStyle: "GridFooter",
    columns: grid.Columns
    (
    grid.Column("Author", "Author", format: @<text>@item.Author</text>),
    grid.Column("Picture", "Picture",format: @<img src="@Url.Content(item.AuthorPic)" alt="Image" />),
    grid.Column("Message", "Message"),
    grid.Column("TimePosted", "TimePosted"),
     grid.Column("RetweetCount", "RetweetCount"),
    grid.Column("LikesCount", "LikesCount")
        )
        )
    </div>
    <div>
    </div>
</body>
</html>

GetTweets/Views/Tweet/Tweet2.cshtml
@model GetTweets.ViewModel.TweetViewModel
@using Models;

@{
    var grid = new WebGrid(Model.tweets, canPage: true,
        canSort: true, rowsPerPage: 2, ajaxUpdateContainerId: "DivGrid");
    grid.Pager(WebGridPagerModes.NextPrevious);
}
<div id="DivGrid">
    @grid.GetHtml(tableStyle: "Grid", headerStyle: "GridHeader",
    alternatingRowStyle: "AltRow", footerStyle: "GridFooter",
    columns: grid.Columns
    (
    grid.Column("Author", "Author", format: @<text>@item.Author</text>),
    grid.Column("Picture", "Picture", format: @<img src="@Url.Content(item.AuthorPic)" alt="Image" />),
    grid.Column("Message", "Message"),
    grid.Column("TimePosted", "TimePosted"),
     grid.Column("RetweetCount", "RetweetCount"),
    grid.Column("LikesCount", "LikesCount")
        )
        )
</div>

GetTweets/Views/Tweet/Tweets.cshtml
@model GetTweets.ViewModel.TweetViewModel
@using Models;
@{
    Layout = null;
}
  
        <table id="tbl">
            <tr>
                <td>Author</td>
                <td>Author Pic</td>
                <td>Tweet</td>
                <td>Posted At</td>
                <td>Likes</td>
                <td>Retweets</td>
            </tr>
            <tr ng-repeat="twt in tweets">
                <td>{{twt.Author}}</td>
                <td>{{twt.AuthorPic}}</td>
                <td>{{twt.Message}}</td>
                <td>{{twt.TimePosted}}</td>
                <td>{{twt.LikesCount}}</td>
                <td>{{twt.RetweetCount}}</td>
            </tr>
        </table>
   